### ISSUE TITLE
docs: missing DOI and citation in `refs.bib`

### ISSUE THREAD

**Issue by wang-boyu** [ABSESpy/ABSESpy#36]
Hi, I'm reviewing your JOSS paper and found some missing info in your references. More specifically -

- DOI is missing for paper "Schulze, J., Müller, B., Groeneveld, J., & Grimm, V. (2017). Agent-based modelling of social-ecological systems: Achievements, challenges, and a way forward. _Journal of Artificial Societies and Social Simulation_, 20(2), 8."
- The paper cited Mesa-Geo but it's not included in the `refs.bib` file.

On a side note, it would be nice if you could format the references is a consistent way, either all in title case, or all in sentence case, but not a mix of both. For example,

**Sentence case:** Beckage, B., Moore, F. C., & Lacasse, K. (2022).  Incorporating human behaviour into Earth system modelling. ...

**Title Case:** Beckage, B., Moore, F. C., & Lacasse, K. (2022). Incorporating Human Behaviour into Earth System Modelling. ...

But this is not strictly required; just something nice to have for your own consideration. It's not blocking the paper review.

**Comment by jamesdamillington** [comment]
On line 99 of the [JOSS proof](https://github.com/openjournals/joss-reviews/issues/6298) there is a reference to _wang2022_ that is missing (this may be the same reference @wang-boyu refers to in their [second bullet point](https://github.com/ABSESpy/ABSESpy/issues/36#issue-2128584274)). Please add this reference.

**Comment by SongshGeo** [comment]
Thanks for the explanation by @jamesdamillington; yep, the reference to `mesa-geo` was not rendered because it lacked a `bib` item. It would be arrogant if I totally ignored `mesa-geo` but invited @wang-boyu  to review this repo, LOL. 

The behavior of the case-sensitive problem was because when exporting the `.bib` file, a 'keep case' option was selected. 

Now everything is fixed in PR #38.
